apiVersion: v1
kind: Pod
metadata:
  name: redisdupa
  namespace: default
  labels:
    app: redis
spec:
  containers:
    - name: redisdupa
      image: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    app: redis
